### ISSUE TITLE
issue with Desktop.lnk

### ISSUE THREAD

**Issue by micprz** [strayge/pylnk#13]
I have found this new issue for homedir/Links/Desktop.lnk, that was created by Windows.

```
>>> lnk4 = pylnk3.Lnk(r'c:\Users\heznik\Links\Desktop.lnk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\msys64\mingw64\lib\python3.8\site-packages\pylnk3.py", line 1501, in __init__
    self._parse_lnk_file(f)
  File "C:\msys64\mingw64\lib\python3.8\site-packages\pylnk3.py", line 1548, in _parse_lnk_file
    self.shell_item_id_list = LinkTargetIDList(lnk.read(shell_item_id_list_size))
  File "C:\msys64\mingw64\lib\python3.8\site-packages\pylnk3.py", line 904, in __init__
    self._interpret(raw)
  File "C:\msys64\mingw64\lib\python3.8\site-packages\pylnk3.py", line 907, in _interpret
    if raw[0][0] == 0x1F:
IndexError: list index out of range
```

I attach file for inspection.
[Desktop.lnk.zip](https://github.com/strayge/pylnk/files/5613149/Desktop.lnk.zip)

**Comment by strayge** [comment]
fix 2bb2759548354bea81a01d8204bfebbdc36de143 in master
